version: '2'

networks:
    lan_0:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/24
                  gateway: 172.19.0.21

services :
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    networks:
        lan_0:
            ipv4_address: 172.19.0.22
    links:
      - php7
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php7
    volumes_from:
      - php7
    ports:
      - 80:80
      - 443:443

  php7:
    build:
      context: ./php7
    container_name: php7
    restart: always
    networks:
        lan_0:
            ipv4_address: 172.19.0.23
    extra_hosts:
            - "local.diamanteslingerie.com.br:172.19.0.22"
    volumes:
      - ./nginx/public_html:/var/www/html
      - ~/Projects:/var/www
    depends_on:
      - mariadb
      - mongodb
    links:
      - mariadb
      - mongodb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    networks:
        lan_0:
            ipv4_address: 172.19.0.24
    volumes:
      - ./mariadb/db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306

  mongodb:
   image: mongo:latest
   command: -smallfiles -nojournal
   container_name: mongodb
   restart: always
   networks:
        lan_0:
            ipv4_address: 172.19.0.25
   volumes:
     - ./mongodb/db-data:/var/lib/mongodb
   ports:
     - 27017:27017
